---
title: "Chiken Chili"
date: '`r Sys.time()`'
output: 
  pagedown::html_paged:
    css: 
    - "../www/mye.css"
    - "../www/mye-page.css"
    - "../www/mye-fonts.css"
knit: pagedown::chrome_print
---

## Chiken Chili

<span class="mh">Servings:</span> 3-4 servings 
<br>

<span class="mh">Ingredients:</span>  
<div class="my2cols">
<ul>
  <li>1 TBSP canola or olive oil</li>
  <li>2-3 cups of fresh oyster mushrooms, bite size pieces</li>
  <li>1&frac12; tsp chili powder</li>
  <li>1 tsp cumin</li>
  <li>1 tsp paprika</li>
  <li>28oz no-salt added diced tomatoes</li>
  <li>1 14oz can of no-salted added black beans</li>
  <li>1 14oz can of no-salted added red beans</li>
  <li>4oz can minced green chilis</li>
  <li>1 cup yellow whole kernel corn</li>
  <li>salt and pepper to taste</li>
  <li>2 'cans' of water (using cans from beans)</li>
</ul>
</div>
<br>
<span class="mh">Directions:</span> 
<div class="my2cols">
<ol>
  <li>In a pot, saute 2-3 cups of oyster mushrooms in 1 TBSP oil over medium-high heat for ~3 minutes</li>
  <li>Stir in spices:
    <ul>
      <li>1&frac12; tsp chili powder</li>
      <li>1 tsp cumin</li>
      <li>1 tsp paprika</li>
    </ul>Coat mushrooms and saute for additional 3-4 minutes
  </li>
  <br>
  <li>Add remaining ingredients and heat through:
    <ul>
      <li>28oz no-salt added diced tomatoes</li>
      <li>1 14oz can of no-salted added black beans</li>
      <li>1 14oz can of no-salted added red beans</li>
      <li>4oz can minced green chilis</li>
      <li>1 cup yellow whole kernel corn</li>
      <li>salt and pepper to taste</li>
      <li>2 'cans' of water </li>
    </ul>
  </li>
</ol>
</div>


<span class="mh">Source:</span> Vegan-ize Chicken Chili recipe from Brad Diamond, also includes edits that Dad/Mom made to recipe
