---
title: "Spicy Tofu Stew"
date: '`r Sys.time()`'
output: 
  pagedown::html_paged:
    css: 
    - "../www/mye.css"
    - "../www/mye-page.css"
    - "../www/mye-fonts.css"
knit: pagedown::chrome_print
---

## Spicy Tofu Stew

<span class="mh">Servings:</span> 3 servings (will make more depending on amount of veggies)
<br>

<span class="mh">Ingredients:</span>  
<div class="my2cols">
<ul>
  <li>1&frac12; TBSP toasted sesame oil</li>
  <li>Small onion, sliced</li>
  <li>&frac12; cup sliced scallion or green onions</li>
  <li>2-3 cloves of garlic, minced</li>
  <li>2 TBSP gochugaro (korean hot pepper powder)</li>
  <li>2&frac12; TBSP tamari</li>
  <li>&frac34; cup vegan kimchi</li>
  <li>Medium zucchini, cubed</li>
  <li>3 cups of mushrooms<br>mix of enoki, king oaster, shiitake</li>
  <li>3 cups water (or veggie broth)</li>
  <li>&frac12; tsp salt</li>
  <li>1 pack silken tofu, cut into cubes</li>
  <li>Additional veggies:
    <ul>
      <li>bok choy (go in with zucchini)</li>
      <li>nappa cabbage (go in with zucchini)</li>
      <li>spinach (go in right before tofu)</li>
    </ul>
  </li>
</ul>
</div>
<br>
<span class="mh">Directions:</span> 
<div class="my2cols">
<ol>
  <li>Heat pot</li>
  <li>One pot is hot, add:
    <ul>
      <li>1&frac12; TBSP toasted sesame oil</li>
      <li>Small onion, sliced</li>
      <li>&frac12; cup sliced scallion or green onions</li>
    </ul>Saute for 2-3 minutes; until onion is translucent 
  </li>
  <li>Add to pot:
    <ul>
      <li>2-3 cloves of garlic, minced</li>
      <li>2 TBSP gochugaro (Korean hot pepper powder)</li>
      <li>2&frac12; TBSP Tamari</li>
    </ul>Stir and cook for 2 minutes 
  </li>
  <li>Add &frac34; cup vegan kimchi<br>Stir and cook for 2-3 minutes</li>
  <li>Add 3 cups of mushrooms<br>Stir and cook for 3 minutes</li>
  <li>Add zucchini cubed and mix well</li>
  <li>Add 3 cups of water (or veggie broth)</li>
  <li>Cover pot and leave to boil over medium heat for about 7 minutes; until the zucchini is cooked through</li>
  <li>Taste and add salt as needed</li>
  <li>Add spinach and mix in</li>
  <li>Add pack of silken tofu, cubed<br>DO NOT MIX (silken tofu is delicate)<br>Leave to boil for 2-3 minutes</li>
</ol>
</div>


<span class="mh">Notes:</span> Good with brown rice

<span class="mh">Source:</span>
<a href = "https://thefoodietakesflight.com/sundubu-jjigae-or-korean-soft-tofu-stew-vegan-recipe/" target="_blank">The Foodie Takes Flight</a>
