---
title: "Three Sisters Soup"
date: '`r Sys.time()`'
output: 
  pagedown::html_paged:
    css: 
    - "../www/mye.css"
    - "../www/mye-page.css"
    - "../www/mye-fonts.css"
knit: pagedown::chrome_print
---

## Three Sisters Soup

<span class="mh">Servings:</span> 
<br>

<span class="mh">Ingredients:</span>  
<div class="my2cols">
<ul>
  <li>1 TBSP olive oil</li>
  <li>3 cloves of garlic</li>
  <li>Large sweet onion</li>
  <li>2&frac12; cups diced carrots</li>
  <li>2&frac12; cups diced celery</li>
  <li>2&frac12; cups diced potatoes, <i>Prefer purple potatoes</i></li>
  <li>2&frac12; cups diced winter squash, <i>Prefer delicata</i></li>
  <li>4 cups veggie broth</li>
  <li>14oz can of coconut milk</li>
  <li>14oz can of corn</li>
  <li>14oz can of navy beans</li>
  <li>1-2 TBSP of parsley</li>
  <li>3 tsp nutmeg</li>
  <li>Salt and pepper, to taste</li>
</ul>
</div>
<br>
<span class="mh">Directions:</span> 
<div class="my2cols">
<ol>
  <li>Heat 1 TBSP olive oil in large pot over medium heat</li>
  <li>Add to pot:
    <ul>
      <li>3 cloves of garlic</li>
      <li>Large sweet onion</li>
      <li>2&frac12; cups diced carrots</li>
      <li>2&frac12; cups diced celery</li>
    </ul>Saute for about 10 minutes
  </li>
  <li>ADd to pot:
    <ul>
      <li>2&frac12; cups diced potatoes</li>
      <li>2&frac12; cups diced winter squash</li>
      <li>4 cups veggie broth</li>
      <li>14oz can of coconut milk</li>
    </ul>
  </li>
  <li>Bring to the pot to just before a boil, then reduce heat and simmer for about 30 minutes (until veggies are fork tender)</li>
  <li>Add to the pot:
    <ul>
      <li>14oz can of corn</li>
      <li>14oz can of navy beans</li>
      <li>1-2 TBSP of parsley</li>
      <li>3 tsp nutmeg</li>
      <li>Salt and pepper, to taste</li>
    </ul>
  </li>
  <li>Cook for a few more minutes until everything is heated through and serve</li>
</ol>
</div>


<span class="mh">Notes:</span> Good with bread or homemade croutons

<span class="mh">Source:</span> Based on soup from co-op in St. Peter, MN
