---
title: "Mexican Rice"
date: '`r Sys.time()`'
output: 
  pagedown::html_paged:
    css: 
    - "../www/mye.css"
    - "../www/mye-page.css"
    - "../www/mye-fonts.css"
knit: pagedown::chrome_print
---

## Mexican Rice 

<span class="mh">Servings:</span> 3-6 servings
<br>

<span class="mh">Ingredients:</span>  
<div class="my2cols">
<ul>
  <li>1.5 TBSP oil</li>
  <li>1.25 cup uncooked long grain rice, <i>OR &frac34; cup white rice and &frac12; cup brown rice</i></li>
  <li>1.5 cup vegetable broth, <i>decrease to 1 cup if mixing rice types</i> </li>
  <li>1 TBSP tomato paste</li>
  <li>0.5 tsp onion powder</li>
  <li>0.5 tsp garlic powder</li>
  <li>0.5 tsp cumin</li>
  <li>0.25 tsp chili powder</li>
  <li>0.25 tsp black pepper</li>
  <li>0.25 tsp salt</li>
</ul>
</div>
<br>
<span class="mh">Directions:</span> 
<div class="my2cols">
<ol>
  <li>If mixing rice, heat up 1 cup water and &frac12; cup brown rice; bring to a boil, then cover and simmer for 25 min</li>
  <li>Heat oil in pan over medium-high heat </li>
  <li>Add white rice to pan, stir constantly until rice starts to turn golden brown</li>
  <li>Add broth, tomato paste and all spices (and brown rice if using).  Mix into rice.</li>
  <li>Bring to a boil, stirring tomato paste so it disolves.</li>
  <li>Turn heat to low, cover, and simmer for 20 min</li>
  <li>Remove from heat and fluff with a fork</li>
</ol>
</div>


<span class="mh">Source:</span>  
<a href = "https://thewoksoflife.com/mexican-rice-recipe/" target="_blank">Mexican Rice by The Works of Life</a>


<span class="mh">Time:</span> 30-60 min 
