---
format: 
  typst: 
    toc: false 
    echo: false 
    margin:
      x: 1cm
      y: 1cm
    fontsize: 10pt 
    mainfont: Ubuntu Mono
editor: source
---
```{=typst}
#pagebreak()
```

## Refried Beans  

| Servings | Time | Source |
|:---|:---|:-------------------|
| ~3 cups  | 40-60 min | N/A | 


### Ingredients:

- 1 cup dry pinto beans
- &frac12; tsp salt
- 1&frac23; cups water 

### Directions 

- In the morning cover the beans with hot water, soak for 6-8 hours 
- put beans into instant pot with 1&frac23; water and salt 
- cook on high for 16-20 minutes, natural release of pressure (~20 minutes) 
- blend beans & liquid for ~45-60 seconds 

Can make without soaking beans by putting directly into instant pot for 60 minutes and ~3 cups of water
  
## Beans in Instant Pot 

Source: [Spice Cravings](https://spicecravings.com/instant-pot-beans) 


Best to soak beans for 8-12 hours. 
I usually soak beans 6-8 hours in hot water (adding more hot water 1-2 times).  

### Beans:Water Ratio 

- 1:2 if beans are soaked, 8 hours 
- 1:3 if beans are not soaked  


### Dry:Cook Ratio 

| Dry | Cooked | Cans | 
|:---|:----|:---------|
| 2 cups | 6 cups | ~3 cans| 
| &frac34; cup or heaping &frac12; cup |  1&frac12; cups | ~1 can | 


### Cook Time by Bean 

| Bean | Time, soaked | Time, unsoaked | 
|:-----|:----:|:----:|
| Chickpeas/Garbanzo | 15 | 40 | 
| Kidney | 25 | 45 | 
| Black | 22 | 35 | 
| Pinto | 15 | 30 | 
