---
title: "MYE Receipe Book"
subtitle: "Last updated: `r Sys.Date()`"
format: 
  typst: 
    toc: true
    toc-depth: 2
    echo: false 
    margin:
      x: 1cm
      y: 1cm
    fontsize: 10pt 
    mainfont: Ubuntu Mono
  html: 
    toc: true
    toc-depth: 2
    echo: false 
    embed-resources: true 
editor: source
---

```{=typst}
#pagebreak()
```

# Favorites 

- [Burrito Bowls](#burrito-bowls)
- [Mushroom Stroganoff](#mushroom-stroganoff)
- [Pesto Pasta](#pesto-pasta)
- [Spaghetti](#spaghetti)
- [Tofu Scramble, Eggy Sauce](#tofu-scramble-v2-eggy-sauce)
- [Spicy Tofu Stew](#spicy-tofu-stew)


```{=typst}
#pagebreak()
```

# MAIN 

```{r}
#| results: asis
out <- knitr::knit_child("main/alfredo.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/bakedtofu.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/bibimbap.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/burritobowls.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/cheezymac.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/eggsbasil.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/herbquinoachickpea.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/mangobluequinoa.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/mushroomstroganoff.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/peanutstirfry.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/pestopasta.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/shepherdspie.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/spaghetti.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/spagsquash.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/tofuscramblev1.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/tofuscramblev2.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/tomatobasilpasta.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("main/veganmeatballs.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{=typst}
#pagebreak()
```

# SOUP 

```{r}
#| results: asis
out <- knitr::knit_child("soup/chikenchili.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("soup/peanutstew.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("soup/potatoleek.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("soup/spicytofustew.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("soup/threesisterssoup.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("soup/veggiechili.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{=typst}
#pagebreak()
```

# SIDES 

```{r}
#| results: asis
out <- knitr::knit_child("side/garlicbread.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("side/hummus.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("side/kalesalad.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("side/mexicanrice.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("side/potatoleaves.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("side/refriedbeans.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("side/squashseeds.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{=typst}
#pagebreak()
```

# DESSERT 

```{r}
#| results: asis
out <- knitr::knit_child("dessert/peanutbuttercookies.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("dessert/pistachiocookies.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("dessert/sweetsquash.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```

```{r}
#| results: asis
out <- knitr::knit_child("dessert/worldseasiestcookies.qmd", quiet = TRUE, envir = environment())
cat(unlist(out), sep = "\n")
```
