---
title: "MYE Recipes<br><span style='font-size: 0.67em'>Recipes that I use on a regular basis<span>" 
date: "<span style='text-align:center'>`r Sys.Date()`</div>"
output: 
  pagedown::html_paged:
    toc: true
    toc_depth: 2
    css: 
    - "www/mye.css"
    - "www/mye-page.css"
    - "www/mye-fonts.css"
---

# Main 

```{r child="main/alfredo.Rmd"}
```

```{r child="main/bakedtofu.Rmd"}
```

```{r child="main/bibimbap.Rmd"}
```

```{r child="main/burritobowls.Rmd"}
```

```{r child="main/cheezymac.Rmd"}
```

```{r child="main/eggsbasil.Rmd"}
```

```{r child="main/herbquinoachickpea.Rmd"}
```

```{r child="main/mangobluequinoa.Rmd"}
```

```{r child="main/mushroomstroganoff.Rmd"}
```

```{r child="main/nocooktomatosauce.Rmd"}
```

```{r child="main/peanutstirfry.Rmd"}
```

```{r child="main/pestopasta.Rmd"}
```

```{r child="main/shepherdspie.Rmd"}
```

```{r child="main/spagandmeatballs.Rmd"}
```

```{r child="main/spagsquash.Rmd"}
```

```{r child="main/tofuscramble.Rmd"}
```

```{r child="main/tofuscramblekimchi.Rmd"}
```

```{r child="main/tomatobasilpasta.Rmd"}
```

```{r child="main/veganmeatballs.Rmd"}
```


# Soup  

```{r child="soup/chikenchili.Rmd"}
```

```{r child="soup/soulsoothingpeanutstew.Rmd"}
```

```{r child="soup/spicytofustew.Rmd"}
```

```{r child="soup/threesisterssoup.Rmd"}
```

```{r child="soup/veggiechili.Rmd"}
```


# Side

```{r child = "side/garlicbread.Rmd"}
```

```{r child = "side/hummus.Rmd"}
```

```{r child = "side/kalesalad.Rmd"}
```

```{r child = "side/mexicanrice.Rmd"}
```

```{r child = "side/potatoleaves.Rmd"}
```

```{r child = "side/refriedbeans.Rmd"}
```

```{r child = "side/squashseeds.Rmd"}
```

```{r child = "side/sweetsqaush.Rmd"}
```

# Dessert 

```{r child = "dessert/peanutbuttercookies.Rmd"}
```

```{r child = "dessert/pistachiocookies.Rmd"}
```