---
title: "Mango Blueberry Quinoa Salad"
date: '`r Sys.time()`'
output: 
  pagedown::html_paged:
    css: 
    - "../www/mye.css"
    - "../www/mye-page.css"
    - "../www/mye-fonts.css"
knit: pagedown::chrome_print
---

## Mango Blueberry Quinoa Salad 

<span class="mh">Servings:</span> 4 servings
<br>

<span class="mh">Ingredients:</span>  
<div class="my2cols">
<ul>
  <li>1 cup of dry quinoa</li>
  <li>2 cup water</li>
  <li>1 cup fresh blueberries</li>
  <li>1 cup cubed ripe mangoes</li>
  <li>1 cup cubed cucumbers</li>
  <li>1 TBSP dried cranberries</li>
  <li>3 TBSP olive oil</li>
  <li>4 TBSP (&frac14; cup) lemon juice</li>
  <li>&frac12; tsp lemon zest</li>
  <li>20 basil leaves, chopped finely</li>
  <li>Salt and pepper to taste</li>
</ul>
</div>
<br>
<span class="mh">Directions:</span> 
<div class="my2cols">
<ol>
  <li>Cook the quinoa.  Place quinoa and water into medium skillet and bring to boil.  Reduce heat and simmer covered fro 15 minutes.  Remove lit and fluff with a fork.  Let cooked quinoa cool to room temperature. </li>
  <li>While quinoa is cooking, combine the following into a bowl and refrigerate until serving: 
    <ul>
      <li>1 cup fresh blueberries</li>
      <li>1 cup cubed ripe mangoes</li>
      <li>1 cup cubed cucumbers</li>
      <li>1 TBSP dried cranberries</li>
    </ul></li>
  <li>Whisk the following dressing ingredients:
    <ul>
      <li>3 TBSP olive oil</li>
      <li>4 TBSP (&frac14; cup) lemon juice</li>
      <li>&frac12; tsp lemon zest</li>
      <li>Salt and pepper</li>
    </ul>Wait to add basil leaves until serving</li>
  <li>Combine all ingredients directly before serving, mix gently.</li>
  <br><br>
</ol>
</div>


<span class="mh">Source:</span>  
<a href = "http://www.veggiebelly.com/2011/06/mango-blueberry-quinoa-salad-with-lemon-basil-dressing-recipe.html" target="_blank">Veggie Belly by Sala</a>
