---
title: "Mushroom Stroganoff"
date: '`r Sys.time()`'
output: 
  pagedown::html_paged:
    css: 
    - "../www/mye.css"
    - "../www/mye-page.css"
    - "../www/mye-fonts.css"
knit: pagedown::chrome_print
---

## Mushroom Stroganoff

<span class="mh">Servings:</span> 4 servings
<br>

<span class="mh">Ingredients:</span>  
<div class="my2cols">
<ul>
  <li>24oz of pasta (2 boxes of penne)</li>
  <li>&frac12;-1 cup vegan butter (stick of Earth balance)</li>
  <li>1 large white onion, diced</li>
  <li>10oz cremini mushrooms, sliced thinly</li>
  <li>3 cloves garlic</li>
  <li>&frac14; - &frac12; cup vegan sour cream or vegan Greek yogurt</li>
  <li>4-5 large portobello mushrooms, thickly sliced7
  <li>2 cups vegan vegetable broth<br><https://www.betterthanbouillon.com/></li>
  <li>8 cups of chopped kale (one bunch worth)</li> 
  <li>&frac12; TBSP Rice vinegar</li>
  <li>&frac12; TBSP Tamari </li>
  <li>Red wine to taste</li>
  <li>1 TBSP fresh rosemary, chopped</li>
  <li>&frac12; tsp salt</li>
  <li>3 TBSP gluten-free flour (to thicken sauce)</li>
  <li>&frac14; cup sour cream</li> 
  <li>2 TBSP fresh parsely, chopped</li>
  <li>1 cup Brown/black lentils</li>
</ul>
</div>
<br>
<span class="mh">Directions:</span> 
<div class="my2cols">
<ol>
  <li>Start cooking the lentils, 1:3 lentil to water ratio, boil 2-3 min, simmer 25-30 min</li>
  <li>Melt butter in pan</li>
  <li>Add to the pan:
    <ul>
      <li>1 large onion, diced</li>
      <li>3 cloves garlic</li>
      <li>10oz cremini mushrooms, thinly sliced</li>
    </ul>Saute for about 5-10 minutes, until mushrooms have cooked down and onion is translucent
  </li>
  <li>Take mushroom/onion contents from the pan and place into a bowl</li>
  <li> Sautee the kale for 4-5 min; remvoe from pan and place into bowl with mushroom and onions</li> 
  <li>Put 4-5 large portobello mushrooms, thickly sliced into the pan and saute for about 3 minutes</li>
  <li>In an empty bowl mix:
    <ul>
      <li>1 cup veggie broth</li>
      <li>&frac12; TBSP rice vinegar</li>
      <li>&frac12; TBSP tamari</li>
      <li>Splash of red wine</li>
      <li>1 TBSP fresh rosemary, chopped</li>
    </ul>After mixing, add to pan with large portobello mushrooms
  </li>
  <li>Bring mixture to boil and simmer for about 15 minutes (until portobellos reduce in size by about 25%)</li>
  <li>Start cooking the pasta</li> 
  <li>In empty bowl mix:
    <ul>
      <li>1 cup veggie broth</li>
      <li>3 TBSP gluten-free flour</li>
    </ul>After mixing, add to pan
  </li>
  <li>Immediately add the mushroom/onion/kale mixture to the pan as well</li>
  <li>Bring mixture to a boil and stir constantly for about 2 minutes</li>
  <li>Stir in &frac14; cup sour cream, make sure to heat until warm but do not boil<br>
  <i>If tastes too sour, add some sesame oil</i></li>
  <li>Gently mix mushroom mixture with pasta, lentils, toss with 2 TBSP fresh parsley, chopped</li>
</ol>
</div>


<span class="mh">Source:</span> Can't find the original link, only had the recipe written down  

<span class="mh">Time:</span> 40 min prep + 40 min cook = 80 min total 
