---
title: "Pesto Gnoochi"
date: '`r Sys.time()`'
output: 
  pagedown::html_paged:
    css: 
    - "../www/mye.css"
    - "../www/mye-page.css"
    - "../www/mye-fonts.css"
knit: pagedown::chrome_print
---

## Pesto Gnoochi (Trader Joe's) 

<span class="mh">Servings:</span> 2-4 servings
<br>

<span class="mh">Ingredients:</span>  
<div class="my2cols">
<ul>
  <li>1-2 packs of Trader Joe's Califlower Gnoochi</li>
  <li>Trader Joe's or homemade pesto</li>
  <li>handfull of  pine nuts</li>
  <li>freshly grated Parmesean<br><i><a href="https://shop.violifefoods.com/just-like-parmesan" target="_blank">Violife</a></i></li>
  <li>2-3 TBSP olive oil</li>
  <li>8-10 oz of grape/cherry tomatoes</li>
  <li>2 handfuls of kale or spinach</li>
</ul>
</div>
<br>
<span class="mh">Directions:</span> 
<div class="my2cols">
<ol>
  <li>Heat oil in non-stick pan on medium </li>
  <li>Add gnoochi and tomoatoes (whole, not cut) and cook for 9-10 min total, adding ingredients along the way</li>
  <li>At ~3-4 min, add salt and pepper </li>
  <li>At ~3-4 min, add kale (if using kale) </li>
  <li>At ~7 min, add baby kale or spinach (if using baby kale or spinach) 
  <li>At 9-10 min, once gnoochi is cooked through and lightly brown on edges, transfer to bowl with pesto and pine nuts</li> 
  <li>Mix ingridents together and top with parmesan</li>
  
</ol>
</div>


I usually make one serving (bag) at a time for me and Alex since our pan is not big enough for 2 bags of gnoochi


Total A-Z time: 12 minutes per serving (24 minutes for 2 servings)  