---
format: 
  typst: 
    toc: false 
    echo: false 
    margin:
      x: 1cm
      y: 1cm
    fontsize: 10pt 
    mainfont: Ubuntu Mono
editor: source
---
```{=typst}
#pagebreak()
```

## Shepherds Pie 

| Servings | Time | Source |
|:---|:---|:-------------------|
| 2 dinner, 1 lunch  | ~60 min | Can't remember original source  | 


### Ingredients:

- Medium carrot, peeled and diced
- 2 cloves garlic, diced
- Medium yellow onion, diced
- 6-8 oz white mushrooms
- &frac34; cups green or brown  lentils
- 1&frac34; cups veggie broth (1&frac12; cups for lentils and &frac14; cups for mashed potatoes) 
- &frac12; - 1 cup frozen peas
- Potatoes, a shit ton yellow or white
- Black pepper
- 2-3 TBSP vegan butter
- Salt and pepper
- Thyme, dried or fresh
- Paprika for serving

### Directions 

#### Mashed Potatoes

- Peel and quarter the potatoes
- Boil water in medium pan, add a dash of salt and then the diced potatoes
- Reduce heat to medium and cook potatoes until they are tender when pierced with a knife, about 15 minutes
- Drain potatoes and put back into pan
- Add to the potatoes and mash:
  * 1-2 TBSP vegan butter
  * &frac14; cups veggie broth
  * salt and pepper
- Cover and put into oven to keep warm

#### Vegetables and Lentils

- Preheat pan over medium heat
- Once pan is hot, melt 1 TBSP vegan butter and swirl to coat bottom of the pan
- Add the following to pan:
  * Medium carrot, peeled and diced
  * 2 cloves garlic, diced
  * Medium yellow onion, diced
  * Season with salt and pepper, cook until veggies soften (2-3 min)
- Add mushrooms to pan and cook until mushrooms soften (2-3 min)
- Add lentils and 1&frac12; cups veggie broth to the pan.  Season with salt, pepper and thyme.
- Bring mixture to a boil, then reduce heat to a simmer, cover with a lid, and cook until lentils are tender (15-20 minutes for green lentils, 25-30 for brown lentils)
- Stir in green peas, heat through
- Serve on top of mashed potatoes with paprika
  
  