---
format: 
  typst: 
    toc: false 
    echo: false 
    margin:
      x: 1cm
      y: 1cm
    fontsize: 10pt 
    mainfont: Ubuntu Mono
editor: source
---
```{=typst}
#pagebreak()
```

## Spaghetti Squash

| Servings | Time | Source |
|:---|:---|:-------------------|
| 2  | 1.5 hrs | N/A | 


### Ingredients:

- 1 Spaghetti squash 
- 1 onion 
- 3 cloves garlic, mined
- 1 large carrto, diced 
- 2 stalks of celery, diced 
- 1 red bell pepper, diced 
- &frac12; dry black/brown lentils 
- 1&frac12; cup vegetable broths 
- 3+ cups of spinach 
- 1 cup tomoato sauce 
- salt, peper, oregano, basil to taste 

### Directions 

- Cut spaghetti squash in half and scope out seeds
- Put squash face down onto a baking sheet (with parchment paper), and cover top lightly with tin foil
- Bake squash at 400 degrees in oven for 40-60 min (until fork soft)
- When about 30 min out of squash being done, heat a olive oil in pan on medium
- Add onion and garlic, saute fro 3 min
- Add celery and carrots, stir-in and daute for 3 min
- Add bell pepper, salt, pepper, oregano and basil
- Add broth and lentils
- Bring mixture to a boil and boil for 2-3 min
- Reduce heat to simmer, cover pan, simmer for 25 min
- Add tomato sauce and mix
- Once squash is done, scope out into bowl (half into one bowl, other half into another bowl)
- Split mixture in pan between 2 bowls 
  
