---
title: "Ind Recipe"
date: '`r Sys.time()`'
output: 
  pagedown::html_paged:
    css: 
    - "../www/mye.css"
    - "../www/mye-page.css"
    - "../www/mye-fonts.css"
knit: pagedown::chrome_print
---

## Tofu Scrample Kimchi & Potatoes 

<span class="mh">Servings:</span> 2 servings 
<br>

<span class="mh">Ingredients:</span>  
<div class="my2cols">
<ul>
  <li>&frac12; cup of non-dairy milk</li>
  <li>1 TBSP nutritional yeast</li>
  <li>2 TBSP sesame paste or cashew butter</li>
  <li>2 TBSP soy sauce</li>
  <li>1 tsp miso paste</li>
  <li>&frac14; tsp tumeric (for color)</li> 
  <li>&frac12; tsp black salt</li> 
  <li> 16oz extra firm tofu (high protien tofu)</li> 
  <li> 3 scallions, sliced</li>
  <li> bunch of spinach</li>
  <li>1 cup kimchi</li>
  <li>2-4 sweet poatoes</li>
</ul>
</div>
<br>
<span class="mh">Directions:</span> 
<div class="my2cols">
<ol>
  <li>Heat oven to 400 degrees, put sweet potatoes on baking sheet with parchement paper and put in the oven for 40 min</li>
  <li>blend top ingredients (milk-salt) to make eggy sauce</li>
  <li>heat pan on medium, crumble tofu into the pan</li> 
  <li>add eggy sauce and scallions and gently stir for a 1-3 minutes</li>
  <li>cook while stirring regularly for ~5min</li>
  <li>Add spinach and stir until the spinach has cooked down, and there is no extra liquid in the pan</li>
  <li>turn off stove, mix in kimchi</li> 
</ol>
</div>

<span class="mh">Time:</span> 40 min 

<span class="mh">Source:</span>
<a href = "https://www.okonomikitchen.com/kimchi-tofu-scramble" target="_blank">Okonomi Kitchen, 2020</a>
