---
title: "Tomato Basil Pasta"
date: '`r Sys.time()`'
output: 
  pagedown::html_paged:
    css: 
    - "../www/mye.css"
    - "../www/mye-page.css"
    - "../www/mye-fonts.css"
knit: pagedown::chrome_print
---

## Tomato Basil Pasta

<span class="mh">Servings:</span> 3 servings
<br>

<span class="mh">Ingredients:</span>  
<div class="my2cols">
<ul>
  <li>&frac12; cup raw cashews</li>
  <li>125 g soft tofu (about 1/3 of package)</li>
  <li>12 oz of penne pasta</li>
  <li>olive oil</li>
  <li>1 small onion, diced</li>
  <li>2-3 cloves garlic</li>
  <li>28 oz can of diced tomatoes</li>
  <li>1 TBSP tomato paste</li>
  <li>2.5-3 TBSP of nutritional yeast</li>
  <li>3 handfuls of spinach</li>
  <li>1 cup packed fresh basil, finely chopped</li>
  <li>1 tsp of dried oregno </li>
  <li>&frac12; tsp salt</li>
  <li>&frac14; tsp black pepper</li>
</ul>
</div>
<br>
<span class="mh">Directions:</span> 
<div class="my2cols">
<ol>
  <li>Soak cashews in water for at least 2 hours (or in hot water for 30 min becasue you forgot)</li>
  <li>Place cashews, tofu, tomato paste, nutritional yeast, oregno, salt, pepper, and juice from canned tomatoes into blender.  Blend on high for 1 min and set aside.  Add more water to mixture if not liquid enough.</li>
  <li>Heat oil in pan on medium</li>
  <li>Add onion and garlic and saute for 5- 10 minutes (until onion is translucent)</li>
  <li>Add diced tomatoes and spinach and continue cooking for 7-10 minutes</li>
  <li>If cooking pasta at same time, put pasta in water after adding tomatoes/spinach to pan.</li>
  <li>Stir in cashew cream and basil, cook for 5-10 minutes<li>
  <li>Drain pasta and mix into pan</li>
</ol>
</div>



<span class="mh">Source:</span> Adjusted luxrious tomato-basil pasta receipe from The Oh She Glows Cookbook by Angela Liddon


<span class="mh">Time:</span> ~1 hour

