---
format: 
  typst: 
    toc: false 
    echo: false 
    margin:
      x: 1cm
      y: 1cm
    fontsize: 10pt 
    mainfont: Ubuntu Mono
editor: source
---
```{=typst}
#pagebreak()
```

## Tomato Basil Pasta

| Servings | Time | Source |
|:---|:---|:-------------------|
| 3-4  | 70 min | Based on Oh She Glows by Angela Liddon, 2014, [ohsheglows.com/book](https://ohsheglows.com/book/) | 


### Ingredients:

- &frac12; cup raw cashews
- 125 g soft tofu (about 1/3 of package); or plant-based milk 
- 12 oz of penne pasta
- olive oil
- 1 small onion, diced
- 2-3 cloves garlic
- 28 oz can of diced tomatoes
- 1 TBSP tomato paste
- 2.5-3 TBSP of nutritional yeast
- 3 handfuls of spinach
- 1 cup packed fresh basil, finely chopped
- 1 tsp of dried oregano 
- &frac12; tsp salt
- &frac14; tsp black pepper

### Directions 

- Soak cashews in water for at least 2 hours (or in hot water for 30 min because you forgot)
- Place cashews, tofu, tomato paste, nutritional yeast, oregano, salt, pepper, and juice from canned tomatoes into blender.  Blend on high for 1 min and set aside.  Add more water to mixture if not liquid enough.
- Heat oil in pan on medium
- Add onion and garlic and saute for 5- 10 minutes (until onion is translucent)
- Add diced tomatoes and spinach and continue cooking for 7-10 minutes
- If cooking pasta at same time, put pasta in water after adding tomatoes/spinach to pan.
- Stir in cashew cream and basil, cook for 5-10 minutes
- Drain pasta and mix into pan
  
