---
title: "Ind Recipe"
date: '`r Sys.time()`'
output: 
  pagedown::html_paged:
    css: 
    - "../www/mye.css"
    - "../www/mye-page.css"
    - "../www/mye-fonts.css"
knit: pagedown::chrome_print
---

## Vegan Meatballs 

<span class="mh">Servings:</span> 4 servings (12 meatballs, 3 meatballs = serving)
<br>

<span class="mh">Ingredients:</span>  
<div class="my2cols">
<ul>
  <li>1 cup cooked & cooked quinoa</li>
  <li>15 oz can black beans</li>
  <li>2 TBSP oil</li> 
  <li>3 cloves garlic</li>
  <li>&frac12; cup shallot</li> 
  <li>&frac14; salt </li> 
  <li>2&frac12; fresh oregano or 1&frac14; dry oregano</li>
  <li>&frac12; tsp red pepper flake</li>
  <li>&frac12; tsp ground fennel/fennel seeds</li> 
  <li>&frac12; cup vegan parm: 6 TBSP cashews, 1.5 TBSP nooch, 3/8 tsp salt, 1/8 tsp garlic powder</li> 
  <li>2 TBSP tomato paste</li> 
  <li>3 TBSP fresh herbs (parsley or basil)</li> 
</ul>
</div>
<br>
<span class="mh">Directions:</span> 
<div class="my2cols">
<ol>
  <li>MORNING: in a small pot add &frac13; cup quinoa and &frac23; cup water, bring to a boil then cover and simmer for 15 min.  Shut off stove and set aside</li> 
  <li>Make vegan parmesian by blending all ingrediets into a food processor</li>
  <li>Heat oven to 350 degrees, rinse black beans and put on a baking sheet with parchment paper, cook for 15 min</li>
  <li>heat small pan on stove over medium heat, add oil, then garlic and shallots, stir and cook for 2-3 min</li> 
  <br><br>
  <li>Group 1 into food processor -- gently blend into a loose meal 
    <ul>
      <li>black beans</li> 
      <li>oil/garlic/shallot</li>
      <li>salt/oregano/red pepper/fennel</li>
    </ul>
  </li>
  <li>Group 2 into food processor -- gently blend into a textured dough 
    <ul>
      <li>quinoa</li> 
      <li>vegan parm</li>
      <li>tomato paste/fresh herbs</li>
    </ul>
  </li>
  <li>Roll into 12 individiual meatballs, then cool in the fridge for at least 15 min</li> 
  <li>Heat oven to 375 degrees, bake meatballs for 20-30 min</li> 
</ol>
</div>

<span class="mh">Time:</span> 1 hr 

Storing for later: After cooling, wrap in parchment paper and put into freezer

<span class="mh">Source:</span>
<a href = "https://minimalistbaker.com/the-best-vegan-meatballs/" target="_blank">Minimalist Baker, The Best Vegan Meatballs</a>
