---
format: 
  typst: 
    toc: false 
    echo: false 
    margin:
      x: 1cm
      y: 1cm
    fontsize: 10pt 
    mainfont: Ubuntu Mono
editor: source
---
```{=typst}
#pagebreak()
```

## Vegan Meatballs  

| Servings | Time | Source |
|:---|:---|:-------------------|
| 4 servings  | 60-75 min | Minimalist Baker, [minimalistbaker.com/the-best-vegan-meatballs](https://minimalistbaker.com/the-best-vegan-meatballs/) | 



### Ingredients:

- 1 cup cooked & cooked quinoa
- 15 oz can black beans
- 2 TBSP oil
- 3 cloves garlic, minced 
- &frac12; cup shallot/onion, minced 
- &frac14; salt 
- 2&frac12; fresh oregano or 1&frac14; dry oregano
- &frac12; tsp red pepper flake
- &frac12; tsp ground fennel/fennel seeds 
- &frac12; cup vegan parm: 6 TBSP cashews, 1.5 TBSP nutritional yeast, 3/8 tsp salt, 1/8 tsp garlic powder
- 2 TBSP tomato paste
- 3 TBSP fresh herbs (parsley or basil)
- flax egg (1 TBSP flax + 3 TBSP water, sit for 15 minutes) 


### Directions 

- MORNING: in a small pot add &frac13; cup quinoa and &frac23; cup water, bring to a boil then cover and simmer for 15 min.  Shut off stove and set aside. 
- Make vegan parm & dry by blending all ingredients into a food processor, put into a bowl 
  * 6 TBSP cashews 
  * 1.5 TBSP nutritional yeast 
  * &frac58; tsp salt (heavy &frac12; tsp) 
  * &frac18; tsp garlic 
  * 1&frac14; dry oregano (if not using fresh)
  * &frac12; tsp red pepper flake
  * &frac12; tsp ground fennel/fennel seeds 
- Heat oven to 350 degrees, rinse black beans and put on a baking sheet with parchment paper, cook for 15 min
- heat small pan on stove over medium heat, add oil, then garlic and shallots, stir and cook for 2-3 min  
- once cool add garlic/shallots into bowl, mix
- add tomato paste to bowl, mix 
- once cool lightly blend black beans and add to bowl, mix
- add quinoa to bowl, mix 
- finally add flax egg to bowl and mix 
- Roll into 12 individual meatballs, then cool in the fridge for at least 15 min
- Heat oven to 375 degrees, bake meatballs for 20-30 min

Once cool, put in freezer for storage. 
 
