---
title: "Veggie Chili"
date: '`r Sys.time()`'
output: 
  pagedown::html_paged:
    css: 
    - "../www/mye.css"
    - "../www/mye-page.css"
    - "../www/mye-fonts.css"
knit: pagedown::chrome_print
---

## Veggie Chili 

<span class="mh">Servings:</span> 6 servings (each approximately 2 cups) 
<br>

<span class="mh">Ingredients:</span>  
<div class="my2cols">
<ul>
  <li>2 TBSP olive oil</li>
  <li>4 cloves garlic, minced</li>
  <li>Large onion, diced</li>
  <li>3 bell peppers (red, yellow, orange), diced</li>
  <li>2 carrots, peeled and diced</li>
  <li>2 stalks celery, diced</li>
  <li>Jalapeno, seeded and diced</li>
  <li>1 tsp ground oregano</li>
  <li>1 TBSP cumin</li>
  <li>2 TBSP chili powder (more/less to taste)</li>
  <li>3 cups veggie broth<br><i></i><a href="https://www.betterthanbouillon.com/" target="_blank">Vegan veggie</a></li>
  <li>1 can (12-14oz) plain tomato sauce</li>
  <li>1 can (10oz) Ro-tel or <br>4oz diced green chilies \& 8oz diced tomatoes</li>
  <li>&frac12; tsp salt (more/less to taste)</li>
  <li>1 can (14oz) kidney beans</li>
  <li>1 can (14oz) pinto beans</li>
  <li>1 can (14oz) garbanzo beans</li>
  <li>1 can (14oz) black beans</li>
  <li>Large zucchini, diced</li>
  <li>&frac14; Masa (corn flour) or cornmeal</li>
  <li>&frac12; cup warm water</li>
</ul>
</div>
<br>
<span class="mh">Directions:</span> 
<div class="my2cols">
<ol>
  <li>Heat 2 TBSP olive oil in large soup pot over medium heat</li>
  <li>Add the following: 
    <ul>
        <li>4 cloves garlic, minced</li>
        <li>Large onion, diced</li>
        <li>3 bell peppers, diced</li>
        <li>2 carrots, peeled and diced</li>
        <li>2 stalks celery, diced</li>
        <li>Jalapeno, seeded and diced</li>
    </ul> Saute for 5 minutes (until starting to soften)
  </li>
  <li>Add the following:
    <ul>
      <li>1 tsp ground oregano</li>
      <li>1 TBSP cumin</li>
      <li>2 TBSP chili powder (more/less to taste)</li>
    </ul> Stir/cook for a few more minutes
  </li>
  <li>Add the following items: 
    <ul>
      <li>3 cups of veggie broth</li>
      <li>1 can (12-14oz) plain tomato sauce</li>
      <li>Ro-tel (or diced tomatoes and chilies)</li>
      <li>&frac12; tsp salt</li>
    </ul>
  </li>
  <li>Bring to a boil then reduce heat to low<br>Cover and simmer for 30 minutes</li>
  <li>Add the following
    <ul>
      <li>1 can (14oz) kidney beans</li>
      <li>1 can (14oz) pinto beans</li>
      <li>1 can (14oz) garbanzo beans</li>
      <li>1 can (14oz) black beans</li>
      <li>Large zucchini, diced</li>
    </ul> Stir in, cover, and simmer for 30 more minutes
  </li>
  <li>Mix in together:
    <ul>
      <li>&frac14; Masa (corn flour) or cornmeal</li>
      <li>&frac12; cup warm water</li>
    </ul> 
  </li>
  <li>Pour corn/water mixture into the pot and stir<br>Simmer for 15 more minutes </li>
  <br><br><br><br>
</ol>
</div>


<span class="mh">Notes:</span> Good with brown rice mixed in


<span class="mh">Source:</span> <a href = "https://www.thepioneerwoman.com/food-cooking/recipes/a11980/veggie-chili/" target="_blank">Pioneer Woman</a>
