---
title: "Peanut Butter Cookies"
date: '`r Sys.time()`'
output: 
  pagedown::html_paged:
    css: 
    - "../www/mye.css"
    - "../www/mye-page.css"
    - "../www/mye-fonts.css"
knit: pagedown::chrome_print
---

## Peanut Butter Cookies

<span class="mh">Servings:</span> 12 cookies 
<br>

<span class="mh">Ingredients:</span>  
<div class="my2cols">
<ul>
  <li>1&frac14; cups gf flour (brown rice or oat)</li>
  <li>&frac12; tsp baking soda</li>
  <li>&frac12; tsp salt (Himalayan pink)</li>
  <li>&frac12; cup creamy peanut butter</li>
  <li>&frac12; cup maple syrup</li>
  <li>&frac14; cup olive oil</li>
  <li>&frac12; tsp vanilla extract</li>
</ul>
</div>
<br>
<span class="mh">Directions:</span> 
<div class="my2cols">
<ol>
  <li>Preheat oven to 350 degrees F and line a baking sheet with parchment paper</li>
  <li>In a bowl combine dry ingredients:
    <ul>
      <li>1&frac14; cups gf flour</li>
      <li>&frac12; tsp baking soda</li>
      <li>&frac12; tsp salt</li>
    </ul>
  </li>
  <li>In another bowl, combine wet ingredients:
    <ul>
      <li>&frac12; cup creamy peanut butter</li>
      <li>&frac12; cup maple syrup</li>
      <li>&frac14; cup olive oil</li>
      <li>&frac12; tsp vanilla extract</li>
    </ul>
  </li>
  <br><br>
  <li>Pour the dry ingredients over the wet ingredients and stir until barely combine<br>
    <i>Still look a bit dusty, avoid over stirring</i>
  </li>
  <li>Let the dough sit for 5 minutes and then give it one more quick stir</li>
  <li>Drop the dough by heaping TBSP onto parchment paper.  Gently press down on each with the back of a fork to get crisscross effect. 
    <br><i>If dough is sticking, run fork and/or TBSP under hot water before use</i>
  </li>
  <li>Bake for 10 minutes, let the cookies cool for an additional 10 minutes before removing from the baking sheet</li>
</ol>
</div>


<span class="mh">Source:</span>
<a href = "https://americanlifestylemag.com/food-recipes/desserts/guilt-free-gluten-free-peanut-butter-cookies/" target="_blank">American Lifestyle Magazine<br></a>
